# Generated by Django 5.2.10 on 2026-01-31 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voiceprofile',
            old_name='fingerprint_json',
            new_name='embedding_json',
        ),
    ]
